print('Welcome to the Mad Lib Game')
name=input('Enter a name:')
place=input('Enter a place:')
adjective=input('Enter a adjective:')
animal=input('Enter a animal name:')
verb=input('Enter a verb')
print('Here is your story!!')
print(f"One day, {name} went to {place} with a {adjective} {animal}.")
print(f"Suddenly, the {animal} decided to {verb} very loudly!")
print(f"Everyone around started to laugh, and {name} couldn't stop smiling.")